server:
  port: 8999

spring:
  # swagger option
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  # jpa setting
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create

    properties:
      database: mysql
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

    database-platform: org.hibernate.dialect.MySQL8Dialect

  # mysql server setting
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/hyundaitransys
    driver-class-name: com.mysql.cj.jdbc.Driver